---

  - name: Build jenkins ansible image
    docker_image:
      path: "/home/{{ ci_user }}/ci/jenkins"
      name: jenkins_ansible
    become: true

  - name: Run jenkins container
    docker_container:
      name: jenkins
      image: jenkins_ansible
      published_ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - "/opt/jenkins:/var/jenkins_home"
      env:
        JENKINS_OPTS: --prefix=/jenkins
      networks:
        - name: cinet
      restart_policy: unless-stopped
      # Remove security opts, if not running Chrome
      # https://hub.docker.com/r/justinribeiro/chrome-headless/
      # https://github.com/jessfraz/dotfiles/blob/master/etc/docker/seccomp/chrome.json
      security_opts:
        - "seccomp: {{ lookup('file', 'chrome.json') | safe }}"
    become: true
