---

  - name: Fix locale problem
    command: update-locale LANGUAGE="en_US.UTF-8" LC_ALL="en_US.UTF-8"
    become: true

  - name: Install openjdk
    apt:
      name: openjdk-8-jdk
      state: latest
    become: true

  - name: Install git
    apt:
      name: git
      state: latest
    become: true

  - name: Include jetty tasks
    include: jetty.yml
    become: true

  - name: Include apache2 tasks
    include: apache.yml
    become: true
