---

  - name: Create app directory
    file:
      path: "{{ ansible_env.HOME }}/{{ app_name }}"
      state: directory

  - name: Copy repository files
    synchronize:
      src: ../../../../../
      dest: "{{ ansible_env.HOME }}/{{ app_name }}"
      checksum: yes

  - name: Run npm install
    npm:
      path: "{{ ansible_env.HOME }}/{{ app_name }}/"
      production: yes

  - name: Start app, if it is not started
    command: pm2 start server.js --name {{ app_name }} chdir={{ ansible_env.HOME }}/{{ app_name }}/
    register: pm2startresult
    changed_when: "'Done' in pm2startresult.stdout"
    failed_when: pm2startresult.rc != 0 and not "'Script already launched' in  pm2startresult.stderr"

  - name: Restart app
    command: pm2 restart {{ app_name }} chdir={{ ansible_env.HOME }}/{{ app_name }}/
    when: pm2startresult.rc != 0
