---

  - name: Install npm
    apt:
      name: npm
      state: latest
    become: true

  - name: Make node symlink
    file:
      src: /usr/bin/nodejs
      dest: /usr/bin/node
      owner: root
      group: root
      state: link
    become: true

  - name: Install pm2 globally
    npm:
      name: pm2
      global: yes
    become: true

  - name: Install git
    apt:
      name: git
      state: latest
    become: true

  - name: Include apache2 tasks
    include: apache.yml
    become: true
