---

  - name: Create app directory
    file:
      path: "{{ ansible_env.HOME }}/{{ app_name }}"
      state: directory

  - name: Copy repository files
    synchronize:
      src: ../../../../
      dest: "/home/{{ ci_user }}"
      checksum: yes

  - name: Install app requirements
    pip:
      requirements: "{{ ansible_env.HOME }}/{{ app_name }}/requirements.txt"
      virtualenv: "{{ ansible_env.HOME }}/{{ app_name }}/venv"

  - name: Create django db migrations
    django_manage:
      command: makemigrations
      app_path: "{{ ansible_env.HOME }}/{{ app_name }}"

  - name: Migrate django db
    django_manage:
      command: migrate
      app_path: "{{ ansible_env.HOME }}/{{ app_name }}"

  - name: Restart app
    file:
      path: "{{ ansible_env.HOME }}/{{ app_name }}/{{ app_name }}/wsgi.py"
      state: touch
