---

  - name: restart jetty
    service:
      name: jetty
      state: restarted
    become: true

  - name: restart apache2
    service:
      name: apache2
      state: restarted
    become: true
