---

  - name: Fix locale problem
    command: update-locale LANGUAGE="en_US.UTF-8" LC_ALL="en_US.UTF-8"
    become: true

  - name: Generate ssh key for user
    user:
      name: "{{ ci_user }}"
      generate_ssh_key: yes

  - name: Fetch public key from user to var
    command: "cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub"
    register: pubkey

  - name: Copy CI files
    synchronize:
      src: ../../../../ci
      dest: "{{ ansible_env.HOME }}"
      checksum: yes

  - name: Create Jenkins directory
    file:
      path: /opt/jenkins
      state: directory
      owner: "{{ ci_user }}"
      group: "{{ ci_user }}"
    become: true

  - name: Set variables for app deployment
    template:
      src: deploy-app-vars.yml.j2
      dest: /opt/jenkins/deploy-app-vars.yml

  - name: Set inventory for app deployment
    template:
      src: hosts.j2
      dest: /opt/jenkins/ansible-hosts

  - name: Copy ssh keypair to jenkins dir
    command: "cp -r {{ ansible_env.HOME }}/.ssh/ /opt/jenkins/"
    args:
      creates: /opt/jenkins/.ssh/

  - name: Install git
    apt:
      name: git
      state: latest
    become: true
